// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// check_names
SEXP check_names(List x, int column_count);
RcppExport SEXP RPresto_check_names(SEXP xSEXP, SEXP column_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type column_count(column_countSEXP);
    __result = Rcpp::wrap(check_names(x, column_count));
    return __result;
END_RCPP
}
// transpose
List transpose(List x, List out);
RcppExport SEXP RPresto_transpose(SEXP xSEXP, SEXP outSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type out(outSEXP);
    __result = Rcpp::wrap(transpose(x, out));
    return __result;
END_RCPP
}
