# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

#' @include PrestoDriver.R PrestoConnection.R
NULL

#' @param drv A driver object generated by [Presto()]
#' @param catalog The catalog to be used
#' @param schema The schema to be used
#' @param user The current user
#' @param host The presto host to connect to
#' @param port Port to use for the connection
#' @param source Source to specify for the connection
#' @param session.timezone Time zone to use for the connection. Presto returns
#'          timestamps without time zones with respect to this value. The time
#'          arithmetic (e.g. adding hours) will also be done in the given time
#'          zone. See the session.timezone tests for examples.
#' @param parameters A [list()] of extra parameters to be passed in
#'          the \sQuote{X-Presto-Session} header
#' @param request.config An optional config list, as returned by
#'          `httr::config()`, to be sent with every HTTP request.
#' @param use.trino.headers A boolean to indicate whether Trino request headers
#'          should be used. Default to FALSE.
#' @param extra.credentials Extra credentials to be passed in the
#'          X-Presto-Extra-Credential or X-Trino-Extra-Credential header (
#'          depending on the value of the use.trino.headers argument). Default
#'          to an empty string.
#' @param bigint The R type that Presto's 64-bit integer (`BIGINT`) class should
#'          be translated to. The default is `"integer"`, which returns R's
#'          `integer` type, but results in `NA` for values above/below
#'          +/-2147483647. `"integer64"` returns a [bit64::integer64], which
#'          allows the full range of 64 bit integers. `"numeric"` coerces into
#'          R's `double` type but might result in precision loss. Lastly,
#'          `"character"` casts into R's `character` type.
#' @param ... currently ignored
#' @return [dbConnect] A [PrestoConnection-class] object
#' @importMethodsFrom DBI dbConnect
#' @importFrom methods new
#' @export
#' @rdname Presto
#' @examples
#' \dontrun{
#' conn <- dbConnect(Presto(),
#'   catalog = "hive", schema = "default",
#'   user = "onur", host = "localhost", port = 8080,
#'   session.timezone = "US/Eastern", bigint = "character"
#' )
#' dbListTables(conn, "%_iris")
#' dbDisconnect(conn)
#' }
#' @md
setMethod(
  "dbConnect",
  "PrestoDriver",
  function(drv,
           catalog,
           schema,
           user,
           host = "localhost",
           port = 8080,
           source = methods::getPackageName(),
           session.timezone = "UTC",
           parameters = list(),
           request.config = httr::config(),
           use.trino.headers = FALSE,
           extra.credentials = "",
           bigint = c("integer", "integer64", "numeric", "character"),
           ...) {
    port <- suppressWarnings(as.integer(port))
    if (!length(port) == 1 || is.na(port)) {
      stop("Please specify a port as an integer")
    }

    conn <- methods::new("PrestoConnection",
      catalog = catalog,
      schema = schema,
      user = user,
      host = host,
      port = port,
      source = source,
      session.timezone = session.timezone,
      request.config = request.config,
      use.trino.headers = use.trino.headers,
      session = PrestoSession$new(parameters),
      extra.credentials = extra.credentials,
      bigint = match.arg(bigint)
    )
    return(conn)
  }
)
