# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

#' @include PrestoDriver.R PrestoConnection.R infer.timezone.R
#' @include verified.timezone.R
NULL

#' @param drv A driver object generated by \code{\link{Presto}}
#' @param catalog The catalog to be used
#' @param schema The schema to be used
#' @param user The current user
#' @param host The presto host to connect to
#' @param port Port to use for the connection
#' @param session.timezone Time zone to use for the connection. Falls back to
#'          the R session's time zone if not specified. If that is also
#'          unavailable, no time zone preference is passed on. In that case,
#'          Presto often uses the local time zone for the cluster by default.
#' @param parameters A \code{\link{list}} of extra parameters to be passed in
#'          the \sQuote{X-Presto-Session} header
#' @param ... currently ignored
#' @return [dbConnect] A \code{\linkS4class{PrestoConnection}} object
#' @export
#' @rdname Presto
#' @examples
#' \dontrun{
#'   conn <- dbConnect(Presto(), catalog = 'hive', schema = 'default',
#'                     user = 'onur', host = 'localhost', port = 8080,
#'                     session.timezone='US/Eastern')
#'   dbListTables(conn, '%_iris')
#'   dbDisconnect(conn)
#' }
setMethod('dbConnect',
  'PrestoDriver',
  function(
    drv,
    catalog,
    schema,
    user,
    host = 'localhost',
    port = 8080,
    session.timezone=NULL,
    parameters = list(),
    ...
  ) {
    port <- suppressWarnings(as.integer(port))
    if (!length(port) == 1 || is.na(port)) {
      stop("Please specify a port as an integer")
    }

    conn <- new('PrestoConnection',
      catalog=catalog,
      schema=schema,
      user=user,
      host=host,
      port=port,
      session.timezone=.infer.timezone(session.timezone),
      parameters=parameters
    )

    conn@session.timezone <- .verified.timezone(conn, session.timezone)

    return(conn)
  }
)
