# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      # Install docker-compose and set up presto/trino servers
      - name: Setup Presto and Trino servers
        uses: ./.github/workflows/setup-presto-trino-servers

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

      # Stop and remove Docker containers
      - name: Stop and remove Docker containers
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
